name: appimagelauncher
version: 'git'
summary: AppImageLauncher allows you to integrate AppImages
description: |
  The core feature of AppImageLauncher is the so-called desktop integration. 
  AppImageLauncher allows you to integrate AppImages you download into your application menu or launcher to make it easier for you to launch them. 
  It also takes care of moving them into a central location, where you can find them later if you need access to them again. 
  Furthermore, it sets up the update and removal entries in the launcher for you.
  
  # snap connection info here

license: MIT

base: core20
grade: stable
confinement: strict

apps:
  appimagelauncher:
    extensions:
      - kde-neon
    command: appimagelauncher
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
     
parts:
  appimagelauncher:
    source: https://github.com/TheAssassin/AppImageLauncher
    source-type: git
    source-subdir: src
    plugin: cmake
    configflags:
    - -DCMAKE_INSTALL_PREFIX=/usr/local/
    
    build-packages:
      - make
      - cmake
      - libglib2.0-0
      - libcairo2-dev
      - librsvg2-dev
      - libfuse-dev
      - libarchive-dev
      - libxpm-dev
      - libcurl4
      - libboost-dev
      - qt5-default
      - inotify-tools
      - libinotifytools0-dev
      - libappimage0
      
    stage-packages:
      - make
      - cmake
      - libglib2.0-0
      - libcairo2-dev
      - librsvg2-dev
      - libfuse-dev
      - libarchive-dev
      - libxpm-dev
      - libcurl4
      - libboost-dev   
      - qt5-default
      - inotify-tools
      - libinotifytools0-dev
      - libappimage0  
